# src/contexts/auth/auth.schema.ts

type User {
	id: String!
	email: String!
	name: String!
	emailVerified: Boolean!
	image: String
	biography: String
	createdAt: DateTimeISO!
}

scalar Upload

input CreateUserInput {
	name: String!
	email: String!
	password: String!
	image: Upload
	imageUrl: String
	biography: String
}
